#!/usr/bin/env python3
from pathlib import Path


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly one match, found {count}: {old!r}")
    path.write_text(text.replace(old, new, 1))


path = Path("src/directory_replay.rs")
replace_once(path, "    fd::{AsFd, OwnedFd},\n", "    fd::OwnedFd,\n")
replace_once(
    path,
    """        let active_key = self.active_key(now)?;\n        let digest = replay_digest(&active_key.material, grant.grant_identifier());\n        let record = encode_record(\n            RECORD_KIND_CONSUME,\n            grant.format_version(),\n            &self.inner.keyring.active_key_id,\n            grant.verification_key_id(),\n            grant.replay_retention_until_unix_seconds(),\n            now,\n            digest,\n            &active_key.material,\n        )?;\n""",
    """        let active_key = self.active_key(now)?;\n        let retention_until_unix_seconds = grant.replay_retention_until_unix_seconds();\n        if retention_until_unix_seconds <= now\n            || retention_until_unix_seconds > active_key.digest_until_unix_seconds\n        {\n            return Err(ReplayConsumeError::KeyUnavailable);\n        }\n        let digest = replay_digest(&active_key.material, grant.grant_identifier());\n        let record = encode_record(\n            RECORD_KIND_CONSUME,\n            grant.format_version(),\n            &self.inner.keyring.active_key_id,\n            grant.verification_key_id(),\n            retention_until_unix_seconds,\n            now,\n            digest,\n            &active_key.material,\n        )?;\n""",
)
replace_once(
    path,
    """        if observed_unix_seconds < key.not_before_unix_seconds\n            || observed_unix_seconds > key.digest_until_unix_seconds\n        {\n            return Err(ReplayConsumeError::CorruptLedger);\n        }\n        let mut digest = [0_u8; DIGEST_BYTES];\n""",
    """        if observed_unix_seconds < key.not_before_unix_seconds\n            || observed_unix_seconds > key.digest_until_unix_seconds\n            || (kind == RECORD_KIND_CONSUME\n                && (retention_until_unix_seconds <= observed_unix_seconds\n                    || retention_until_unix_seconds > key.digest_until_unix_seconds))\n            || (kind == RECORD_KIND_WATERMARK && retention_until_unix_seconds != 0)\n        {\n            return Err(ReplayConsumeError::CorruptLedger);\n        }\n        let mut digest = [0_u8; DIGEST_BYTES];\n""",
)
replace_once(
    path,
    """    #[test]\n    fn replay_keys_are_independent_from_authentication_and_verification_keys() {\n        let directory = tempfile::tempdir().unwrap();\n        let replay_keyring = directory.path().join(\"replay-keys.json\");\n        let (verifier, _) = verifier_and_grant(directory.path(), [0x85_u8; 32]);\n        let config = replay_config(directory.path(), replay_keyring.clone());\n\n        let auth = \"a\".repeat(32);\n        write_replay_keyring(&replay_keyring, auth.as_bytes(), 0o600);\n        assert!(\n            DirectoryReplayLedger::load_optional(&config, Some(&auth), Some(&verifier), NOW,)\n                .is_err()\n        );\n\n        write_replay_keyring(&replay_keyring, &[0x31_u8; 32], 0o600);\n        assert!(DirectoryReplayLedger::load_optional(\n            &config,\n            Some(\"authentication-token\"),\n            Some(&verifier),\n            NOW,\n        )\n        .is_err());\n    }\n}\n""",
    """    #[test]\n    fn replay_keys_are_independent_from_authentication_and_verification_keys() {\n        let directory = tempfile::tempdir().unwrap();\n        let replay_keyring = directory.path().join(\"replay-keys.json\");\n        let (verifier, _) = verifier_and_grant(directory.path(), [0x85_u8; 32]);\n        let config = replay_config(directory.path(), replay_keyring.clone());\n\n        let auth = \"a\".repeat(32);\n        write_replay_keyring(&replay_keyring, auth.as_bytes(), 0o600);\n        assert!(\n            DirectoryReplayLedger::load_optional(&config, Some(&auth), Some(&verifier), NOW,)\n                .is_err()\n        );\n\n        write_replay_keyring(&replay_keyring, &[0x31_u8; 32], 0o600);\n        assert!(DirectoryReplayLedger::load_optional(\n            &config,\n            Some(\"authentication-token\"),\n            Some(&verifier),\n            NOW,\n        )\n        .is_err());\n    }\n\n    #[test]\n    fn retained_record_rejects_early_digest_key_retirement() {\n        let directory = tempfile::tempdir().unwrap();\n        let replay_keyring = directory.path().join(\"replay-keys.json\");\n        let old_key = [0x74_u8; 32];\n        let new_key = [0x75_u8; 32];\n        write_replay_keyring(&replay_keyring, &old_key, 0o600);\n        let (verifier, grant) = verifier_and_grant(directory.path(), [0x86_u8; 32]);\n        let config = replay_config(directory.path(), replay_keyring.clone());\n        let ledger = DirectoryReplayLedger::load_optional(\n            &config,\n            Some(\"authentication-token\"),\n            Some(&verifier),\n            NOW,\n        )\n        .unwrap()\n        .unwrap();\n        ledger.consume(&grant, NOW).unwrap();\n\n        fs::write(\n            &replay_keyring,\n            serde_json::to_vec(&serde_json::json!({\n                \"version\": 1,\n                \"active_kid\": \"replay-key-02\",\n                \"keys\": [\n                    {\n                        \"kid\": \"replay-key-01\",\n                        \"key_b64url\": URL_SAFE_NO_PAD.encode(old_key),\n                        \"not_before_unix_seconds\": NOW - 60,\n                        \"digest_until_unix_seconds\": NOW + 1,\n                    },\n                    {\n                        \"kid\": \"replay-key-02\",\n                        \"key_b64url\": URL_SAFE_NO_PAD.encode(new_key),\n                        \"not_before_unix_seconds\": NOW - 60,\n                        \"digest_until_unix_seconds\": NOW + 600,\n                    }\n                ]\n            }))\n            .unwrap(),\n        )\n        .unwrap();\n        fs::set_permissions(&replay_keyring, fs::Permissions::from_mode(0o600)).unwrap();\n\n        assert!(DirectoryReplayLedger::load_optional(\n            &config,\n            Some(\"authentication-token\"),\n            Some(&verifier),\n            NOW,\n        )\n        .is_err());\n    }\n}\n""",
)
